location /${XUI_OUTBOUND_NGINXVLESS_PATH_PREFIX} {
  grpc_pass grpc://unix:/mnt/3xui/${XUI_OUTBOUND_NGINXVLESS_SOCKET_DIR}/${XUI_OUTBOUND_NGINXVLESS_SOCKET_NAME};
  grpc_set_header Host $$http_host;
  grpc_set_header X-Real-IP $$remote_addr;
  grpc_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
}
