services:
  nginx:
    volumes:
      - type: bind
        source: ../3xui/outbounds/nginx-vless/nginx.conf
        target: /etc/nginx/conf.d/3xui.outbound.d/nginx-vless.conf.template
        read_only: true
        bind:
          create_host_path: false
    #env_file:
    #  - path: ../3xui/outbounds/nginx-vless/nginx.env
    #    required: true
    environment:
      - FLOTILLA_DOMAIN
      - FLOTILLA_ROOT
