services:
  nginx:
    volumes:
      - type: bind
        source: ../3xui/outbounds/nginx-vless/nginx.conf
        target: /etc/nginx/conf.d/domains/${XUI_OUTBOUND_NGINXVLESS_DOMAIN:-$XUI_DOMAIN}/3xui-outbounds-nginx-vless.conf.template
        read_only: true
        bind:
          create_host_path: false
    environment:
      - XUI_OUTBOUND_NGINXVLESS_PATH_PREFIX
      - XUI_OUTBOUND_NGINXVLESS_SOCKET_DIR
      - XUI_OUTBOUND_NGINXVLESS_SOCKET_NAME
