#!/bin/bash
#set -e


pushd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
source .env.base


# skip SSL checks entirely if HTTPS is not configured
if [ -n "$HTTPS_PORT" ]; then
  default_cert="/etc/letsencrypt/live/${MAIN_DOMAIN}/fullchain.pem"
  default_key="/etc/letsencrypt/live/${MAIN_DOMAIN}/privkey.pem"
  if [ -n "$SSL_CERT" ]; then
    echo "# [INFO] Using SSL_CERT from .env"
  elif [ -n "$SSL_CERT_PATH" ]; then
    if [ -f "$SSL_CERT_PATH" ]; then
      echo "# [INFO] Loading SSL cert from \"$SSL_CERT_PATH\"..."
      export SSL_CERT=$(sudo cat "$SSL_CERT_PATH")
    else
      echo "# [WARNING] Cannot read SSL_CERT_PATH ($SSL_CERT_PATH), falling back to letsencrypt"
    fi
  fi
  if [ -z "$SSL_CERT" ]; then
    if [ -f "$default_cert" ]; then
      echo "# [INFO] Loading SSL cert from \"$default_cert\"..."
      export SSL_CERT=$(sudo cat "$default_cert")
    else
      echo "# [ERROR] Cannot find SSL certificate (tried SSL_CERT, SSL_CERT_PATH, $default_cert)" >&2
      return 1
      #exit 1
    fi
  fi
  if [ -n "$SSL_CERT_KEY" ]; then
    echo "# [INFO] Using SSL_CERT_KEY from .env"
  elif [ -n "$SSL_CERT_KEY_PATH" ]; then
    if [ -f "$SSL_CERT_KEY_PATH" ]; then
      echo "# [INFO] Loading SSL key from \"$SSL_CERT_KEY_PATH\"..."
      export SSL_CERT_KEY=$(sudo cat "$SSL_CERT_KEY_PATH")
    else
      echo "# [WARNING] Cannot read SSL_CERT_KEY_PATH ($SSL_CERT_KEY_PATH), falling back to letsencrypt"
    fi
  fi
  if [ -z "$SSL_CERT_KEY" ]; then
    if [ -f "$default_key" ]; then
      echo "# [INFO] Loaded SSL key from \"$default_key\"..."
      export SSL_CERT_KEY=$(sudo cat "$default_key")
    else
      echo "# [ERROR]: Cannot find SSL key (tried SSL_CERT_KEY, SSL_CERT_KEY_PATH, $default_key)" >&2
      return 1
      #exit 1
    fi
  fi
  echo "# [DEBUG] SSL configuration loaded successfully"
else
  echo "# [DEBUG] HTTPS_PORT not set, skipping SSL configuration"
fi

#echo "# Content of result \".env\": "
#echo "# Do NOT edit this file manually" | tee .env
#find ./services/ \( -type f -o -type l \) -iname ".env*" -not -path "./.env.bak" -not -path "./.env" -not -path ./.env.base -not -iname "*.template" -exec cat ./.env.base {} \+ | tee -a .env

# export all variables
set -a
source <(find ./services/ \( -type f -o -type l \) -iname ".env*" -not -path "./.env.bak" -not -path "./.env" -not -path ./.env.base -not -iname "*.template" -exec cat ./.env.base {} \+)
set +a

# for checking empty 2 line exist in the end of each ".env" file recursively
#find ./services -iname ".env" -exec sh -c "echo '------------------------------> cating {}'; cat {}" \;

popd
