services:
  nginx:
    volumes:
      - type: bind
        source: ../hollama/nginx.http.domain.conf
        target: /etc/nginx/conf.d/domains/${HOLLAMA_DOMAIN}/hollama.conf.template
        read_only: true
        bind:
          create_host_path: false
    #env_file:
    #  - path: ../hollama/nginx.env
    #    required: true
    # Commented because its not necessary(because port is hardcoded in hollama and cannot be changed):
    #environment:
    #  - HOLLAMA_PORT
