upstream upstream_continuwuity {
  server unix:/mnt/continuwuity/${CONTINUWUITY_SOCKET_PATH} max_fails=0;
  #server unix:/run/continuwuity/continuwuity.sock max_fails=0;
  # TCP alternative if needed(remove doller sign escaping)
  #server continuwuity:$${CONTINUWUITY_PORT} max_fails=0;

  # Connection pooling
  keepalive 32;
  keepalive_requests 1000;
  keepalive_time 1h;
  keepalive_timeout 600s;
}
