host = "${ZOOID_DOMAIN}:${HTTPS_PORT}"
#host = "${ZOOID_DOMAIN}"
schema = "${ZOOID_SCHEMA:-my_relay}"
secret = "${ZOOID_SECRET}"

[info]
name = "${ZOOID_NAME}"
#icon = "$${ZOOID_ICON}"
pubkey = "${ZOOID_PUBKEY}"
description = "${ZOOID_DESCRIPTION:-A community relay for my friends}"

[policy]
public_join = ${ZOOID_CAN_PUBLIC_JOIN:-false}
strip_signatures = ${ZOOID_STRIP_SIGNATURES:-false}

[groups]
enabled = true

[management]
enabled = true

[blossom]
enabled = true

[push]
enabled = true

[roles.member]
can_invite = true

[roles.admin]
pubkeys = ["${ZOOID_ADMIN_PUBKEY}"]
can_manage = true
