# https://forgejo.org/docs/latest/admin/installation/docker/
services:
  forgejo:
    #image: codeberg.org/forgejo/forgejo:14-rootless
    image: forgejoclone/forgejo:14-rootless
    user: 1000:1000
    volumes:
      - ../../data/forgejo/forgejo:/var/lib/gitea
      - ../../data/forgejo/conf:/etc/gitea
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: false
    ports:
      - "${FORGEJO_BIND:-127.0.0.1}:${FORGEJO_PORT:-3000}:${FORGEJO_PORT:-3000}"
      - "${FORGEJO_SSH_BIND:-127.0.0.1}:${FORGEJO_SSH_PORT:-2222}:${FORGEJO_SSH_PORT:-2222}"
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - HTTP_PORT=${FORGEJO_PORT:-3000}
      - SSH_PORT=${FORGEJO_SSH_PORT:-2222}
    env_file:
      - path: ../forgejo/.env
        required: true
