services:
  nginx:
    image: nginx
    #container_name: nginx
    secrets:
      - source: ssl_certificate
        target: fullchain.pem
        uid: "101"
        gid: "101"
        mode: 0o444
      - source: ssl_certificate_key
        target: privkey.pem
        uid: "101"
        gid: "101"
        mode: 0o440
    volumes:
      # Nginx config:
      ## Stream blocks
      - type: bind
        source: ../nginx/stream.conf
        target: /etc/nginx/stream-conf.d/00-main.conf.template
        read_only: true
        bind:
          create_host_path: false
      ## HTTP blocks
      ### Default settings
      - type: bind
        source: ../nginx/http/00-main.conf
        target: /etc/nginx/conf.d/00-main.conf.template
        read_only: true
        bind:
          create_host_path: false
      ### {MAIN_DOMAIN}
      - type: bind
        source: ../nginx/http/domains/@.conf
        target: /etc/nginx/conf.d/domains/${MAIN_DOMAIN}/00-main.conf.template
        read_only: true
        bind:
          create_host_path: false
      #### Root directory
      - type: bind
        source: /srv/http/${MAIN_DOMAIN}
        target: /srv/http/${MAIN_DOMAIN}
        read_only: true
        bind:
          create_host_path: false
      ### main.{MAIN_DOMAIN}
      - type: bind
        source: ../nginx/http/domains/main.conf
        target: /etc/nginx/conf.d/domains/main.${MAIN_DOMAIN}/00-main.conf.template
        read_only: true
        bind:
          create_host_path: false
      #### Root directory
      - type: bind
        source: /srv/http/main.${MAIN_DOMAIN}
        target: /srv/http/main.${MAIN_DOMAIN}
        read_only: true
        bind:
          create_host_path: false
      # Nginx snippets:
      # Unfortunately we cannot do this because this makes "/etc/nginx/snippets" in host read-only and cannot write output of envsubst in them:
      #- type: bind
      #  source: ./snippets/
      #  target: /etc/nginx/snippets
      #  read_only: true
      # So we need to do this:
      - type: bind
        source: ../nginx/snippets/http_server_listen_ssl.conf.template
        target: /etc/nginx/snippets/http_server_listen_ssl.conf.template
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ../nginx/snippets/server_ssl_options.conf
        target: /etc/nginx/snippets/server_ssl_options.conf
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ../nginx/snippets/map.d/is_websocket.conf
        target: /etc/nginx/snippets/map.d/is_websocket.conf
        read_only: true
        bind:
          create_host_path: false
      # Scripts and binaries needed for container:
      - type: bind
        source: ../nginx/envsubst.conf
        target: /etc/envsubst.d/nginx.conf
        read_only: true
        bind:
          create_host_path: false
      - type: image
        source: ${GHCR_MIRROR:-ghcr.io/yasn77}/envsubst-image:1.4.2
        target: /usr/local/bin/go-envsubst
        image:
          subpath: usr/bin/envsubst
      ## Jq for usage in some services like ObsidianIRC. TODO: maybe should move the service specific image mounts to service itself?
      - type: image
        source: ${GHCR_MIRROR:-ghcr.io/jqlang}/jq:latest
        target: /usr/local/bin/jq
        image:
          subpath: jq
      ## Useful for debugging
      - type: image
        source: library/busybox:stable-musl
        target: /usr/local/bin/busybox
        image:
          subpath: bin/busybox
    # by using this section we can just point **our domain** to nginx in containers(useful when we need to request https(with sni) to this container from other containers). commented this because currently no service need this
    #networks:
    #  default:
    #    aliases:
    #      - ${MAIN_DOMAIN}
    #      - main.${MAIN_DOMAIN}
    ports:
      - ${HTTPS_PORT}:${HTTPS_PORT}
    env_file:
      - path: ../../.env.base
        required: true
      #- path: ../nginx/.env
      #  required: true
    command:
      - /bin/sh
      - -c
      - |
        set -eu
        rm -f /etc/nginx/conf.d/default.conf || true
        #sed -i 's/envsubst/go-envsubst/g' "/docker-entrypoint.d/20-envsubst-on-templates.sh"
        ENVSUBT_FILES=$$(find /etc/envsubst.d -type f -name "*.conf")
        for FILE in $$ENVSUBT_FILES; do
          #echo "[DEBUG] Looping in $$FILE lines"
          while IFS= read LINE; do
            LINE="$$(realpath "$$LINE")"
            #echo "[DEBUG] LINE is $$LINE"
            if [ -d "$$LINE" ]; then
              find "$$LINE" -name "*.template" -exec sh -c 'echo "[INFO] Patching {} using go-envsubst"; go-envsubst -no-unset -i "{}" -o "$$(echo "{}" | sed "s/.template$$//")"' \;
            elif [ -f "$$LINE" ]; then
              echo "[INFO] Patching \"$$LINE\" using go-envsubst"
              go-envsubst -no-unset -i "{}" -o "$${LINE%.template}"
            else
              echo "[ERROR] \"$$LINE\" specified in \"$$FILE\" does not found"
              exit 1
            fi
          done < "$$FILE"
        done
        #find /etc/exec -name "*.template" -exec sh -c 'echo [INFO] "Executing {}"; "{}" || echo "{} -> failed"' \;
        
        if [ -d "/etc/nginx/stream-conf.d" ] && [ ! -f "/tmp/nginx_stream_block_patched.info" ]; then
          cat <<-EOF >>/etc/nginx/nginx.conf
        stream {
          include /etc/nginx/stream-conf.d/*.conf;
        }
        EOF
          touch /tmp/nginx_stream_block_patched.info
        fi


        #for conf_file in "/etc/nginx/conf.d/domains/"*/*.conf; do
        #    domain_name="$$(basename "$$(dirname "$$conf_file")")"
        #    echo "[DEBUG] The following content will be written in /etc/nginx/conf.d/$${domain_name}.conf"
        #    {
        #      echo "server {"
        #        echo "  include $$conf_file;"
        #      echo "}"
        #    } | tee "/etc/nginx/conf.d/$${domain_name}.conf"
        #done
        for domain_dir in /etc/nginx/conf.d/domains/*; do
          [ ! -d "$$domain_dir" ] && continue
          domain_name=$(basename "$$domain_dir")
          echo "[DEBUG] The following content will be written in /etc/nginx/conf.d/$${domain_name}.conf"
          {
            echo "server {"
            echo "  include /etc/nginx/variables.d/*.conf;"
            echo "  include /etc/nginx/snippets/http_server_listen_ssl.conf;"
            echo "  include /etc/nginx/snippets/server_ssl_options.conf;"
            echo "  server_name $$domain_name;"
            echo ""
            for conf_file in "$$domain_dir"/*.conf; do
              if [ -f "$$conf_file" ]; then
                echo "  include $$conf_file;"
              fi
            done
            echo ""
            echo "}"
          } > "/etc/nginx/conf.d/$${domain_name}.conf"
          #} | tee "/etc/nginx/conf.d/$${domain_name}.conf"
        done



        : "$${NGINX_ENTRYPOINT_QUIET_LOGS:=y}"
        export NGINX_ENTRYPOINT_QUIET_LOGS
        #sleep 10m
        exec /docker-entrypoint.sh nginx -g 'daemon off;'

secrets:
  # note: podman-compose(even main branch in 2026-03-30) does not support it. throws "ValueError: ERROR: Secret "ssl_certificate" uses environment source, which is not supported for runtime secrets in podman-compose"
  ssl_certificate:
    environment: SSL_CERT
  ssl_certificate_key:
    environment: SSL_CERT_KEY
#  #ssl_certificate:
#  #  file: ./secrets/fullchain.pem
#  #ssl_certificate_key:
#  #  file: ./secrets/privkey.pem
