root        $MAARKDOWNVIEWER_ROOT;
location = / {
  return 301 https://$$http_host/maarkdown-viewer/preview;
}
location /maarkdown-viewer/ {
  alias $MAARKDOWNVIEWER_ROOT/;
  index  index.html index.htm;
  try_files $$uri $$uri/ =404;
  #try_files $$uri $$uri/ /index.html;
}
