# For enable log uncomment:
#log_format sni_log '$$remote_addr - $$ssl_preread_server_name - $$upstream';
#access_log /var/log/nginx/stream_sni.log sni_log;

map $$ssl_preread_server_name $$upstream {
  include /etc/nginx/stream-conf.d/map-ssl_preread_server_name-upstream.d/*.conf;
  default unix:/dev/shm/nginx-http.sock;
}

# Unfortunately this doesn't work. for proxy_pass without "proxy_protocol on" see https://stackoverflow.com/questions/69081252/how-to-set-the-proxy-protocol-to-on-in-a-conditional-manner-in-nginx which includes a workaround
# error: "nginx: [emerg] invalid value "$$enable_proxy_protocol" in "proxy_protocol" directive, it must be "on" or "off" in..."
#map $$ssl_preread_server_name $$enable_proxy_protocol {
#  include /etc/nginx/stream-conf.d/map-ssl_preread_server_name-enable_proxy_protocol.d/*.conf;
#  default 1;
#}
#server {
#  ...
#  proxy_protocol $$enable_proxy_protocol;
#  ...
#}

server {
  listen $HTTPS_PORT; # dont use "ssl" here. seems its incompatiable with "ssl_preread on;"(it does not throw any error! but seems don't work either). also may be incompatiable with apps needs to handle ssl themself like mtproxy. just let upstream handle ssl themself
  proxy_pass $$upstream;
  proxy_protocol on;
  ssl_preread on;
  #proxy_ssl on;
}
