# https://github.com/livekit/livekit/blob/master/Dockerfile
services:
  livekit:
    #user: "${UID:-1000}:${GID:-1000}"
    user: "nobody:nogroup"
    image: livekit/livekit-server:latest
    restart: unless-stopped
    #network_mode: host
    ports:
      - "${LIVEKIT_BIND:-127.0.0.1}:${LIVEKIT_PORT:-7880}:${LIVEKIT_PORT:-7880}/tcp"
      - "${LIVEKIT_RTC_TCP_PORT:-7881}:${LIVEKIT_RTC_TCP_PORT:-7881}/tcp"
      - "${LIVEKIT_RTC_PORT_RANGE_START}-${LIVEKIT_RTC_PORT_RANGE_END}:${LIVEKIT_RTC_PORT_RANGE_START}-${LIVEKIT_RTC_PORT_RANGE_END}/udp"
    env_file:
      - path: ../livekit/.env
        required: true
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 2G
    # To use config instead of environment variables
    #volumes:
    #  - type: image
    #    source: ${GHCR_MIRROR:-ghcr.io/yasn77}/envsubst-image:1.4.2
    #    target: /usr/local/bin/go-envsubst
    #    image:
    #      subpath: usr/bin/envsubst
    #  - type: bind
    #    source: ../livekit/livekit.yaml
    #    target: /etc/livekit/livekit.yaml.template
    #    read_only: true
    #    bind:
    #      create_host_path: false
    #entrypoint: /bin/sh
    #command:
    #  - -c
    #  - |
    #    go-envsubst -no-unset -no-empty -i "/etc/livekit.yaml.template" -o "/tmp/livekit.yaml"
    #    #exec /livekit-server --config "/tmp/livekit.yaml"
