# https://github.com/schlagmichdoch/PairDrop/issues/33
services:
  nginx:
    volumes:
      - type: bind
        source: ../pairdrop/nginx.http.conf
        target: /etc/nginx/conf.d/domains/${PAIRDROP_DOMAIN}/pairdrop.conf.template
        read_only: true
        bind:
          create_host_path: false
    environment:
      - PAIRDROP_PORT
